POST http://localhost:3000/sql-query/test2
Content-Type: application/json

{
  "ACCOUNT_ID" : 23,
  "SOURCE" : [1, 2, 3, 4, 5],
  "CREATED_AT" : {
    "BEGIN":"2025-12-08",
    "END":"2025-12-08"
  },
  "STATUS" : true
}
